### PR TITLE
[push-voting-power] Added support for tokens staked in Push V2 pool

### LINKED ISSUE #1424: Update voting power strategy after Push V2
### Expected behavior
- Currently the push-voting-power supports push v1 token and Lp pairs.
### Actual behavior
- Last year Push Protocol introduced Push V2 for staking PUSH and Uniswap V2 LP pair tokens.
### Steps to reproduce the behavior
- The current snapshot strategy doesn't take PUSH staked in V2 smart contract and Uniswap V2 LP tokens into calculations for voting power.

### PR DESCRIPTION
**Pull request by aeyshubh**
Fixes #1424 

Changes proposed in this pull request:
- Added support for counting voting power according to the user's PUSH tokens that are staked in V2 Pool
- Added support for counting voting power according to the UniV2 LP tokens Staked on Push V2

### CODE REVIEW

File: src/strategies/push-voting-power/index.ts [hunk 1]
```diff
@@ -2,8 +2,10 @@ import { formatUnits } from '@ethersproject/units';
 import { BigNumber } from '@ethersproject/bignumber';
 import { multicall } from '../../utils';
 
-export const author = 'mujtaba1747';
-export const version = '0.1.0';
+//0.1.0 was authered by mujtaba1747
+
+export const author = 'aeyshubh';
```
Comment (ChaituVR) [inline src/strategies/push-voting-power/index.ts:7]:
```suggestion
export const author = 'ethereum-push-notification-service';
```

**Review by ChaituVR — CHANGES_REQUESTED** [review]

**Review by ChaituVR — APPROVED** [review]
